[features]
seeds = false
skip-lint = false
[programs.devnet]
commonmarket = "7N6EPRN8bWZBgnDhxShPbfDqrGXUjCDRvqiGTpaUtc33"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/MainAccount.ts"
sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Sell.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Check.ts"
exchange = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Exchange.ts"
update = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/UpdateSupply.ts"
delete = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/DeleteSell.ts"