[features]
seeds = false
skip-lint = false
[programs.devnet]
solotery = "FMz7qxxUeqgCKZL2z96nBhp6mpyisdVEEuS4ppZG3bmH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Create.ts"
ticket = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Ticket.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Check.ts"