[features]
seeds = false
skip-lint = false
[programs.devnet]
solotery = "CEBJ4Yj5z4dB3ahZBVTbo6kUmykh3HqibCjyNzRugUmj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Blockchain/Create.ts"
winner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Blockchain/ChooseWinner.ts"
ticket = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Users/OneTicket.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Users/CheckIt.ts"
send = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Blockchain/SendAmountToWinner.ts"
buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Users/BuyShare.ts"